language: ruby
rvm:
    - 2.2
before_script:
    - gem install awesome_bot
script:
    - awesome_bot README.md --white-list CONTRIBUTING.md,amzn.com,balccon.org,amazon.com,clean-mx.de,zoomeye.org,andrototal.org,domaintools.com,reconstructer.org,reddit.com,desenmascara.me,exploit-db.com,travis-ci,tekdefense.com,winitor.com,https://zoomeye.org,handlers.sans.org,bokken.re
